TASKS = [
    {
        "name": "easy",
        "difficulty": "easy",
        "ticket": "Hi, I ordered a laptop two weeks ago, and the tracking page still says it is in transit. When will it arrive?",
        "expected_category": "delivery",
        "priority": "low",
        "sentiment": "neutral",
        "sla_hours": 48.0,
        "resolution_keywords": ["delivery", "tracking", "shipment", "order"],
        "instructions": "First identify the issue category, then provide a polite delivery update and explain the next step.",
    },
    {
        "name": "medium",
        "difficulty": "medium",
        "ticket": "My replacement headphones arrived damaged and I want a refund. I also need help with returning the broken item.",
        "expected_category": "refund",
        "priority": "medium",
        "sentiment": "frustrated",
        "sla_hours": 24.0,
        "resolution_keywords": ["refund", "return", "exchange", "damage", "return label"],
        "instructions": "First classify the issue, then write a supportive resolution that offers the correct refund or return process.",
    },
    {
        "name": "hard",
        "difficulty": "hard",
        "ticket": "I was charged twice for my subscription renewal and then locked out of my account. I cannot access premium features and need urgent help.",
        "expected_category": "account",
        "priority": "high",
        "sentiment": "angry",
        "sla_hours": 6.0,
        "resolution_keywords": ["account", "billing", "refund", "unlock", "access", "escalate"],
        "instructions": "First choose the correct category, then craft an urgent response that apologizes, explains the recovery steps, and escalates or resolves the account issue.",
    },
]
